### ISSUE TITLE
Bug in Networkplayer.cs

### ISSUE THREAD

**Issue by srahmel** [readyplayerme/rpm-unity-sdk-netcode-support#7]
Hi!

The method "LoadAvatar" in NetworkPlayer.cs throws errors.

The AvatarMeshHelper.TransferMesh(args.Avatar, gameObject); requires 3 attributes, not 2.
It seems you need to pass the target skinned mesh renderer and the animatior.
Also the readme.md should be updated, because avatar loader is deprecated.

I also had issues with the position of the characters, the poisition was not really updating.

Could you please check?

Thanks!

**Comment by srcnalt** [comment]
Hi @srahmel, this issue must be fixed with the latest release now. Can you check and let me know?

**Comment by srahmel** [comment]
Library\PackageCache\com.readyplayerme.netcodesupport@19631dff41\Runtime\NetworkPlayer.cs(66,34): error CS7036: There is no argument given that corresponds to the required formal parameter 'targetAnimator' of 'AvatarMeshHelper.TransferMesh(GameObject, SkinnedMeshRenderer[], Animator)'

**Comment by srcnalt** [comment]
What is the version of `readyplayerme.core` package are you using? This Netcode update will work with v6.1.0+

**Comment by srahmel** [comment]
The NetworkPlayer.cs seems unchanged. The probkem is on line 66 in NetworkPlayer.cs.
The method AvatarMeshHelper.TransferMesh needs GameObject source, SkinnedMeshRenderer[] targetMeshes, Animator targetAnimator. These are three args.

In line 66 you only have 2 args: AvatarMeshHelper.TransferMesh(args.Avatar, gameObject);

If you open project in Unity with Ready Me it will directly throw these errors

**Comment by srcnalt** [comment]
`AvatarMeshHelper.TransferMesh(args.Avatar, gameObject);` is only available in core package 6.1.0+ you will need to update the core package.

**Comment by srahmel** [comment]
The core package is up to date

![image](https://github.com/readyplayerme/rpm-unity-sdk-netcode-support/assets/14318776/0f7c38a8-c0e7-4d09-b74a-8c3f738fecc9)

**Comment by srahmel** [comment]
Never mind. I reimported everything again, now it works

**Comment by srahmel** [comment]
It seems that I had to delete all folders before updating.
